import type {
  Barbell,
  EquipmentTag,
  Exercise,
  PlateInventory,
  RoutineTemplate,
} from '../types';
import {
  STRONG_CURVES_EXERCISES,
  STRONG_CURVES_ROUTINES,
} from '../seed/strongCurves';
import {
  COMPOUND_EXERCISES,
  STRETCHING_EXERCISES,
} from '../seed/exercisesExtra';
import { EXTRA_ROUTINES } from '../seed/routinesExtra';
import {
  ENRICHMENT,
  EQUIPMENT_BY_PREFIX,
  SIMPLYFITNESS_BASE,
  SIMPLYFITNESS_OVERRIDES,
  SPOTEBI_BASE,
  SPOTEBI_OVERRIDES,
  spotebiSlugFromName,
} from '../seed/exerciseEnrichment';
import { SEED_PROFILES } from '../seed/profiles';
import { SEED_BARBELLS, SEED_PLATE_INVENTORY } from '../seed/equipment';
import { db } from './db';

// On first boot (and on subsequent boots if seeds have changed), upsert
// the built-in profiles, exercise library, routine templates, and
// per-profile equipment defaults into Dexie. Idempotent — safe to run
// on every app load.
//
// Strategy:
//   * Profiles are seeded only if missing — never overwrite the user's
//     edits to their own profile.
//   * Built-in exercises and routines are *replaced* on every load so
//     that bumping the seed (via `pnpm seed:build`) propagates without
//     leaving stale rows. User-created exercises (`isCustom: true`) and
//     custom routines (`isSeed: false`) are left alone.
//   * Equipment (barbells + plate inventory) is additive only —
//     populated for any profile that currently has none, and untouched
//     thereafter so user adjustments stick.
//   * Exercise rows are merged from three sources: the autogenerated
//     Strong Curves library, the hand-written extras (stretching +
//     compound lifts), and an enrichment map (instructions / diagrams /
//     equipment) keyed by id. Later entries override earlier ones — so
//     COMPOUND_EXERCISES takes precedence for any duplicate id, and
//     ENRICHMENT layers on top of both.

const SEED_EPOCH = '2026-05-06T00:00:00.000Z';

type ExerciseSeed = Omit<
  Exercise,
  | 'isCustom'
  | 'profileId'
  | 'requiredEquipment'
  | 'instructions'
  | 'diagram'
  | 'demoUrl'
> & {
  requiredEquipment?: EquipmentTag[];
  instructions?: string[];
  diagram?: string;
  demoUrl?: string;
};

/** Merge the three sources into one canonical list per id. */
function mergeExerciseSources(): ExerciseSeed[] {
  const merged = new Map<string, ExerciseSeed>();

  for (const e of STRONG_CURVES_EXERCISES) {
    merged.set(e.id, { ...e });
  }
  // Hand-written wins over the generated seed for any duplicate id —
  // enables us to author a richer entry for a lift the spreadsheet
  // also defines.
  for (const e of [...COMPOUND_EXERCISES, ...STRETCHING_EXERCISES]) {
    merged.set(e.id, { ...e });
  }

  // Apply enrichment + equipment-by-prefix fallback + auto demoUrl.
  for (const [id, e] of merged) {
    const enrichment = ENRICHMENT[id] ?? {};
    const requiredEquipment =
      enrichment.requiredEquipment ?? e.requiredEquipment ?? equipmentByPrefix(id, e.name);
    const instructions = enrichment.instructions ?? e.instructions;
    const diagram = enrichment.diagram ?? e.diagram;
    // demoUrl resolution order:
    //   1. SPOTEBI_OVERRIDES[id] — populated by URL probing; explicit
    //      `null` means "no spotebi page", explicit string is used
    //      verbatim.
    //   2. enrichment.spotebiSlug — same semantics, lets the
    //      ENRICHMENT map carry per-exercise overrides too.
    //   3. Auto-generated spotebi slug from the exercise name.
    //   4. SIMPLYFITNESS_OVERRIDES[id] — fallback when spotebi is
    //      explicitly suppressed. SimplyFitness has a heavier compound /
    //      barbell catalogue and fills several gaps spotebi can't.
    let demoUrl: string | undefined;
    const explicit =
      id in SPOTEBI_OVERRIDES
        ? SPOTEBI_OVERRIDES[id]
        : enrichment.spotebiSlug;
    if (explicit === null) {
      // Spotebi has no page; try SimplyFitness as a fallback.
      const fallback = SIMPLYFITNESS_OVERRIDES[id];
      if (fallback) demoUrl = `${SIMPLYFITNESS_BASE}${fallback}`;
    } else if (typeof explicit === 'string') {
      demoUrl = `${SPOTEBI_BASE}${explicit}/`;
    } else {
      const slug = spotebiSlugFromName(e.name);
      if (slug) demoUrl = `${SPOTEBI_BASE}${slug}/`;
    }
    merged.set(id, {
      ...e,
      requiredEquipment,
      ...(instructions ? { instructions } : {}),
      ...(diagram ? { diagram } : {}),
      ...(demoUrl ? { demoUrl } : {}),
    });
  }

  return Array.from(merged.values());
}

function equipmentByPrefix(id: string, name: string): EquipmentTag[] {
  for (const rule of EQUIPMENT_BY_PREFIX) {
    if (rule.match(id, name)) return rule.equipment;
  }
  return ['bodyweight'];
}

export async function ensureSeedLoaded(): Promise<void> {
  await db.transaction(
    'rw',
    [
      db.profiles,
      db.exercises,
      db.routineTemplates,
      db.barbells,
      db.plateInventory,
    ],
    async () => {
      // 1. Profiles — additive only.
      const existingProfileIds = new Set(await db.profiles.toCollection().primaryKeys());
      const profilesToAdd = SEED_PROFILES.filter((p) => !existingProfileIds.has(p.id));
      if (profilesToAdd.length > 0) {
        await db.profiles.bulkAdd(profilesToAdd);
      }

      // 2. Exercises — replace seed rows, leave custom rows alone.
      await db.exercises.filter((e) => !e.isCustom).delete();
      const seededExercises: Exercise[] = mergeExerciseSources().map((e) => ({
        ...e,
        requiredEquipment: e.requiredEquipment ?? [],
        isCustom: false,
        profileId: null,
      }));
      await db.exercises.bulkAdd(seededExercises);

      // 3. Routine templates — replace seed rows, leave custom routines alone.
      await db.routineTemplates.filter((r) => r.isSeed).delete();
      const allRoutineSeeds = [...STRONG_CURVES_ROUTINES, ...EXTRA_ROUTINES];
      const seededRoutines: RoutineTemplate[] = allRoutineSeeds.map((r) => ({
        ...r,
        profileId: null,
        createdAt: SEED_EPOCH,
        updatedAt: SEED_EPOCH,
      }));
      await db.routineTemplates.bulkAdd(seededRoutines);

      // 4. Equipment defaults — per profile, additive only.
      const allProfileIds = (await db.profiles.toCollection().primaryKeys()) as string[];
      for (const profileId of allProfileIds) {
        const hasBars = (await db.barbells.where({ profileId }).count()) > 0;
        if (!hasBars) {
          const seededBars: Barbell[] = SEED_BARBELLS.map((b) => ({
            id: crypto.randomUUID(),
            profileId,
            name: b.name,
            weight: b.weight,
            isDefault: b.isDefault,
          }));
          await db.barbells.bulkAdd(seededBars);
        }
        const hasInventory =
          (await db.plateInventory.where({ profileId }).count()) > 0;
        if (!hasInventory) {
          const inv: PlateInventory = {
            id: crypto.randomUUID(),
            profileId,
            plates: [...SEED_PLATE_INVENTORY],
          };
          await db.plateInventory.add(inv);
        }
      }
    },
  );
}
