// Hand-written extras: stretching library + a handful of compound
// exercises that the Strong Curves seed didn't include but the new
// routines (Starting Strength, 5/3/1) reference.
//
// Format matches the existing autogenerated `STRONG_CURVES_EXERCISES`
// shape (`Omit<Exercise, 'isCustom' | 'profileId'>`) so the seed
// loader can merge both lists with the same enrichment pass.

import type { EquipmentTag, Exercise, MuscleGroup } from '../types';

type ExerciseSeed = Omit<Exercise, 'isCustom' | 'profileId'>;

// --- Stretching ------------------------------------------------------------

function stretch(opts: {
  id: string;
  name: string;
  primary: MuscleGroup[];
  secondary?: MuscleGroup[];
  perSide?: boolean;
  equipment?: EquipmentTag[];
  diagram?: string;
  instructions: string[];
}): ExerciseSeed {
  return {
    id: opts.id,
    name: opts.name,
    category: 'stretching',
    primaryMuscles: opts.primary,
    secondaryMuscles: opts.secondary ?? [],
    measurementType: 'time_seconds',
    defaultRestSeconds: 15,
    perSide: opts.perSide ?? false,
    usesBarbell: false,
    requiredEquipment: opts.equipment ?? ['yoga-mat'],
    instructions: opts.instructions,
    ...(opts.diagram ? { diagram: opts.diagram } : {}),
  };
}

export const STRETCHING_EXERCISES: ReadonlyArray<ExerciseSeed> = [
  stretch({
    id: 'stretch-hamstring-supine',
    name: 'Supine Hamstring Stretch',
    primary: ['hamstrings'],
    secondary: ['calves'],
    perSide: true,
    diagram: 'hamstring-stretch',
    instructions: [
      'Lie on your back; loop a strap (or your hands) around one foot.',
      'Straighten the leg toward the ceiling, opposite leg flat.',
      'Hold where you feel a strong stretch but no pinch behind the knee.',
    ],
  }),
  stretch({
    id: 'stretch-hip-flexor-kneeling',
    name: 'Kneeling Hip Flexor Stretch',
    primary: ['adductors'],
    secondary: ['quads', 'glutes'],
    perSide: true,
    diagram: 'hip-flexor-stretch',
    instructions: [
      'Half-kneeling lunge — back knee on a soft surface.',
      'Squeeze the glute on the kneeling side and tuck the pelvis.',
      'Shift weight slightly forward; hold the stretch in the front of the hip.',
    ],
  }),
  stretch({
    id: 'stretch-pigeon',
    name: 'Pigeon Pose',
    primary: ['glutes'],
    secondary: ['hamstrings'],
    perSide: true,
    instructions: [
      'From all-fours, bring one shin forward, foot toward the opposite hand.',
      'Extend the other leg straight back, hips square to the floor.',
      'Walk the hands forward as the stretch allows; breathe.',
    ],
  }),
  stretch({
    id: 'stretch-figure-four',
    name: 'Figure-4 Glute Stretch',
    primary: ['glutes'],
    perSide: true,
    instructions: [
      'Lie on your back, both knees bent.',
      'Cross one ankle over the opposite thigh, just above the knee.',
      'Pull the bottom thigh toward your chest until you feel the stretch.',
    ],
  }),
  stretch({
    id: 'stretch-quad-standing',
    name: 'Standing Quad Stretch',
    primary: ['quads'],
    perSide: true,
    equipment: ['bodyweight'],
    instructions: [
      'Stand tall; grab one foot behind you with the same-side hand.',
      'Pull the heel toward the glute, knees together, hips forward.',
      'Stand near a wall for balance if needed.',
    ],
  }),
  stretch({
    id: 'stretch-cat-cow',
    name: 'Cat–Cow',
    primary: ['core'],
    secondary: ['back'],
    instructions: [
      'On all-fours, hands under shoulders, knees under hips.',
      'Inhale: drop the belly, look up (cow).',
      'Exhale: round the spine, tuck the chin (cat). Flow between.',
    ],
  }),
  stretch({
    id: 'stretch-child-pose',
    name: "Child's Pose",
    primary: ['back'],
    secondary: ['lats'],
    diagram: 'child-pose',
    instructions: [
      'From all-fours, sink the hips back to the heels.',
      'Reach the arms long in front; forehead toward the mat.',
      'Breathe deeply into the back ribs.',
    ],
  }),
  stretch({
    id: 'stretch-downward-dog',
    name: 'Downward Dog',
    primary: ['hamstrings'],
    secondary: ['calves', 'shoulders', 'lats'],
    instructions: [
      'From all-fours, tuck the toes and lift the hips up and back.',
      'Press evenly through the hands; ears between the upper arms.',
      "Pedal the heels if needed — don't force them down.",
    ],
  }),
  stretch({
    id: 'stretch-cobra',
    name: 'Cobra Stretch',
    primary: ['core'],
    secondary: ['chest'],
    instructions: [
      'Lie face down, hands under shoulders.',
      'Press the chest up while the hips stay heavy on the floor.',
      'Pull shoulder blades down the back; only go to a comfortable arch.',
    ],
  }),
  stretch({
    id: 'stretch-thread-needle',
    name: 'Thread the Needle',
    primary: ['back'],
    secondary: ['shoulders', 'lats'],
    perSide: true,
    instructions: [
      'On all-fours, slide one arm under the other, palm up.',
      'Lower the same-side shoulder and ear to the mat.',
      'Press the opposite hand into the floor for a deeper rotation.',
    ],
  }),
  stretch({
    id: 'foam-roll-quads',
    name: 'Foam Roll — Quads',
    primary: ['quads'],
    perSide: true,
    equipment: ['foam-roller'],
    diagram: 'foam-roll',
    instructions: [
      'Face down; roller under one thigh, weight on forearms.',
      'Roll slowly from above the knee to the hip flexor.',
      'Pause on tender spots; flex/extend the knee a few times.',
    ],
  }),
  stretch({
    id: 'foam-roll-lats',
    name: 'Foam Roll — Lats',
    primary: ['lats'],
    perSide: true,
    equipment: ['foam-roller'],
    diagram: 'foam-roll',
    instructions: [
      'Lie on your side, roller in the armpit, top arm extended.',
      'Roll along the lat from armpit to mid-ribs.',
      'Reach the working arm overhead to deepen the stretch.',
    ],
  }),
  stretch({
    id: 'stretch-90-90',
    name: '90/90 Hip Switch',
    primary: ['glutes', 'adductors'],
    perSide: true,
    instructions: [
      'Sit with one leg in front (90° at knee), one out to the side (90°).',
      'Hinge over the front shin and hold; spine long.',
      'Sweep the legs to the other side and repeat.',
    ],
  }),
  stretch({
    id: 'stretch-tspine-rotation',
    name: 'T-Spine Rotation',
    primary: ['back'],
    secondary: ['shoulders'],
    perSide: true,
    instructions: [
      'On all-fours, place one hand behind the head.',
      'Rotate the elbow under the chest, then up to the ceiling.',
      'Eyes follow the elbow; keep the hips square.',
    ],
  }),

  // --- r/flexibility "Starting to Stretch" set --------------------------
  stretch({
    id: 'stretch-shoulder-backbend',
    name: 'Shoulder Backbend',
    primary: ['shoulders'],
    secondary: ['chest'],
    instructions: [
      'Sit with knees bent, feet flat, hands behind you fingertips pointing away.',
      'Press hips up to a tabletop bridge.',
      'Keep arms locked; let the shoulders sink toward the floor.',
    ],
  }),
  stretch({
    id: 'stretch-standing-backbend',
    name: 'Standing Backbend',
    primary: ['back'],
    secondary: ['chest', 'shoulders'],
    instructions: [
      'Stand tall, feet hip-width, hands on the lower back for support.',
      'Inhale tall through the spine, exhale and arch backward — chest leads.',
      "Only go to a comfortable arch; don't crunch the lower back.",
    ],
  }),
  stretch({
    id: 'stretch-rear-hand-clasp',
    name: 'Rear Hand Clasp',
    primary: ['shoulders'],
    secondary: ['chest', 'biceps'],
    perSide: true,
    instructions: [
      'Reach one arm overhead, bend at the elbow so the hand drops behind your back.',
      'Bring the other arm behind from below; clasp the hands (use a strap if they don\'t meet).',
      'Stand tall, ribs down — feel the stretch in shoulders and triceps.',
    ],
  }),
  stretch({
    id: 'stretch-lying-cross',
    name: 'Lying Cross Stretch',
    primary: ['back'],
    secondary: ['glutes'],
    perSide: true,
    instructions: [
      'Lie on your back, arms out in a T.',
      'Cross one knee over the body and let it fall toward the opposite hand.',
      'Keep both shoulders pinned to the floor; turn the head the opposite way.',
    ],
  }),
  stretch({
    id: 'stretch-wrist-biceps',
    name: 'Wrist & Biceps Stretch',
    primary: ['forearms'],
    secondary: ['biceps'],
    instructions: [
      'Kneel, place hands flat on the floor in front of you with fingers pointing toward your knees.',
      'Slowly shift weight backward, keeping palms down.',
      'Feel the stretch through the forearm flexors and into the biceps.',
    ],
  }),
  stretch({
    id: 'stretch-one-leg-pike',
    name: 'One-Leg Pike',
    primary: ['hamstrings'],
    secondary: ['back'],
    perSide: true,
    diagram: 'hamstring-stretch',
    instructions: [
      'Sit with one leg extended forward, foot flexed. Tuck the other foot to the inner thigh.',
      'Hinge at the hips, lengthening the spine forward toward the foot.',
      'Lead with the chest, not the head; back stays flat.',
    ],
  }),
  stretch({
    id: 'stretch-pancake',
    name: 'Pancake Stretch',
    primary: ['hamstrings', 'adductors'],
    secondary: ['back'],
    diagram: 'pancake',
    instructions: [
      'Sit with legs as wide as comfortably possible, feet flexed, knees pointing up.',
      'Hinge at the hips with a flat back; walk the hands forward.',
      "Hold where you feel a strong but tolerable stretch — don't round over.",
    ],
  }),
  stretch({
    id: 'stretch-butterfly',
    name: 'Butterfly Stretch',
    primary: ['adductors'],
    secondary: ['glutes'],
    diagram: 'butterfly',
    instructions: [
      'Sit tall, soles of the feet together, knees out to the sides.',
      'Hold the feet; gently press the knees toward the floor with the elbows.',
      'Hinge forward from the hips for a deeper stretch.',
    ],
  }),
  stretch({
    id: 'stretch-calf',
    name: 'Calf Stretch',
    primary: ['calves'],
    perSide: true,
    diagram: 'calf-stretch',
    instructions: [
      'Stand facing a wall, hands at chest height.',
      'Step one foot back, keeping the heel pressed firmly into the floor.',
      'Bend the front knee slightly; keep the back leg straight, toes pointing forward.',
    ],
  }),
];

// --- Compound exercises the Strong Curves seed lacks -----------------------

function compound(opts: {
  id: string;
  name: string;
  category: Exercise['category'];
  primary: MuscleGroup[];
  secondary?: MuscleGroup[];
  measurementType?: Exercise['measurementType'];
  defaultRestSeconds?: number;
  usesBarbell?: boolean;
  perSide?: boolean;
  equipment: EquipmentTag[];
  diagram?: string;
  instructions: string[];
}): ExerciseSeed {
  return {
    id: opts.id,
    name: opts.name,
    category: opts.category,
    primaryMuscles: opts.primary,
    secondaryMuscles: opts.secondary ?? [],
    measurementType: opts.measurementType ?? 'weight_reps',
    defaultRestSeconds: opts.defaultRestSeconds ?? 120,
    perSide: opts.perSide ?? false,
    usesBarbell: opts.usesBarbell ?? false,
    requiredEquipment: opts.equipment,
    instructions: opts.instructions,
    ...(opts.diagram ? { diagram: opts.diagram } : {}),
  };
}

export const COMPOUND_EXERCISES: ReadonlyArray<ExerciseSeed> = [
  compound({
    id: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    category: 'quad',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'core'],
    usesBarbell: true,
    equipment: ['barbell'],
    diagram: 'squat',
    instructions: [
      'Set the bar on your upper back, just below the rear delts.',
      'Brace, unrack, take two steps back, feet shoulder-width.',
      'Sit between your hips; knees track over toes.',
      'Hip crease at or below the knee, then drive up.',
    ],
  }),
  compound({
    id: 'barbell-front-squat',
    name: 'Barbell Front Squat',
    category: 'quad',
    primary: ['quads', 'glutes'],
    secondary: ['core'],
    usesBarbell: true,
    equipment: ['barbell'],
    diagram: 'squat',
    instructions: [
      'Rack the bar across the front delts, elbows high.',
      'Stay upright through the descent; keep elbows up.',
      'Drive evenly through the whole foot.',
    ],
  }),
  compound({
    id: 'barbell-deadlift',
    name: 'Barbell Deadlift',
    category: 'hip-hinge',
    primary: ['hamstrings', 'glutes', 'back'],
    secondary: ['core', 'forearms', 'traps'],
    usesBarbell: true,
    defaultRestSeconds: 180,
    equipment: ['barbell'],
    diagram: 'deadlift',
    instructions: [
      'Bar over mid-foot, shins ~1 inch from the bar.',
      'Hinge to the bar; grip outside the knees; pull the slack out.',
      'Push the floor away — chest leads.',
      'Lock out by squeezing glutes; lower with control.',
    ],
  }),
  compound({
    id: 'barbell-overhead-press',
    name: 'Barbell Overhead Press',
    category: 'push',
    primary: ['shoulders'],
    secondary: ['triceps', 'core'],
    usesBarbell: true,
    equipment: ['barbell'],
    diagram: 'overhead-press',
    instructions: [
      'Bar racked at the front delts.',
      'Glutes and abs tight; press in a straight line.',
      'Bar finishes overhead with biceps by the ears.',
    ],
  }),
  compound({
    id: 'barbell-power-clean',
    name: 'Power Clean',
    category: 'pull',
    primary: ['glutes', 'hamstrings', 'back', 'shoulders'],
    secondary: ['quads', 'traps', 'core'],
    usesBarbell: true,
    defaultRestSeconds: 180,
    equipment: ['barbell'],
    instructions: [
      'Set up like a deadlift, bar over mid-foot.',
      'Pull explosively; finish the hip extension violently.',
      'Catch the bar in a quarter-front-rack with high elbows.',
    ],
  }),
  compound({
    id: 'barbell-bent-over-row',
    name: 'Barbell Bent-Over Row',
    category: 'pull',
    primary: ['back', 'lats'],
    secondary: ['biceps', 'forearms', 'core'],
    usesBarbell: true,
    equipment: ['barbell'],
    diagram: 'row',
    instructions: [
      'Hinge to ~45°, neutral spine, bar hanging from shoulders.',
      'Pull the bar to the lower ribs, leading with the elbows.',
      'Squeeze the back briefly; lower under control.',
    ],
  }),
  compound({
    id: 'dumbbell-row',
    name: 'One-Arm Dumbbell Row',
    category: 'pull',
    primary: ['back', 'lats'],
    secondary: ['biceps', 'core'],
    perSide: true,
    equipment: ['dumbbells', 'bench'],
    diagram: 'row',
    instructions: [
      'One knee and hand on a bench; opposite leg planted.',
      'Pull the dumbbell toward the hip, leading with the elbow.',
      'Squeeze briefly at the top; control the descent.',
    ],
  }),
  compound({
    id: 'pull-up',
    name: 'Pull-Up',
    category: 'pull',
    primary: ['lats', 'back'],
    secondary: ['biceps', 'forearms'],
    measurementType: 'bodyweight_reps',
    equipment: ['pull-up-bar'],
    diagram: 'pull-up',
    instructions: [
      'Hang with a slightly wider than shoulder grip.',
      'Pull until chin clears the bar; chest leads.',
      'Lower under control to full extension.',
    ],
  }),
  compound({
    id: 'chin-up',
    name: 'Chin-Up',
    category: 'pull',
    primary: ['lats', 'biceps'],
    secondary: ['back', 'forearms'],
    measurementType: 'bodyweight_reps',
    equipment: ['pull-up-bar'],
    diagram: 'pull-up',
    instructions: [
      'Hang palms-toward-you, hands shoulder width.',
      'Pull chest to the bar; squeeze lats + biceps.',
      'Full extension at the bottom — no kipping.',
    ],
  }),
  compound({
    id: 'push-up',
    name: 'Push-Up',
    category: 'push',
    primary: ['chest', 'triceps'],
    secondary: ['shoulders', 'core'],
    measurementType: 'bodyweight_reps',
    defaultRestSeconds: 60,
    equipment: ['bodyweight'],
    diagram: 'push-up',
    instructions: [
      'Hands under shoulders, body in one straight line.',
      'Lower until chest is just off the floor.',
      'Press up explosively; lock out briefly.',
    ],
  }),
  compound({
    id: 'walking',
    name: 'Walking',
    category: 'cardio',
    primary: ['quads', 'glutes', 'calves'],
    secondary: ['hamstrings', 'core'],
    measurementType: 'walking',
    defaultRestSeconds: 0,
    equipment: ['bodyweight'],
    instructions: [
      'Comfortable pace — you should be able to hold a conversation.',
      'Log either a duration, a step count, or both.',
      'Indoor treadmill, outside, on a hike — anything counts.',
    ],
  }),
  compound({
    id: 'running',
    name: 'Running',
    category: 'cardio',
    primary: ['quads', 'hamstrings', 'calves', 'glutes'],
    secondary: ['core'],
    measurementType: 'distance',
    defaultRestSeconds: 0,
    equipment: ['bodyweight'],
    instructions: [
      'Outdoor, treadmill, road, trail — all the same to the log.',
      'Track distance and duration; pace shows up in the share text.',
      'Easy, tempo, intervals — log each as a separate set if you split.',
    ],
  }),
  compound({
    id: 'cycling',
    name: 'Cycling',
    category: 'cardio',
    primary: ['quads', 'glutes', 'hamstrings', 'calves'],
    secondary: ['core'],
    measurementType: 'distance',
    defaultRestSeconds: 0,
    equipment: ['bodyweight'],
    instructions: [
      'Stationary bike, road, MTB — anything that counts as ride time.',
      'Track distance and duration.',
    ],
  }),
  compound({
    id: 'rowing',
    name: 'Rowing',
    category: 'cardio',
    primary: ['back', 'lats', 'glutes', 'hamstrings', 'quads'],
    secondary: ['biceps', 'core', 'shoulders'],
    measurementType: 'distance',
    defaultRestSeconds: 0,
    equipment: ['machine'],
    instructions: [
      'Drive with the legs, then back, then arms; reverse the chain on the recovery.',
      'Track distance and duration — the erg shows you both.',
    ],
  }),
  compound({
    id: 'swimming',
    name: 'Swimming',
    category: 'cardio',
    primary: ['back', 'lats', 'shoulders', 'chest'],
    secondary: ['core', 'glutes', 'quads', 'triceps'],
    measurementType: 'distance',
    defaultRestSeconds: 0,
    equipment: ['bodyweight'],
    instructions: [
      'Any stroke — freestyle, breaststroke, mixed laps.',
      'Distance in metres; convert pool laps as needed (50 m / 25 m pools).',
    ],
  }),
  compound({
    id: 'elliptical',
    name: 'Elliptical',
    category: 'cardio',
    primary: ['quads', 'glutes', 'hamstrings'],
    secondary: ['core', 'shoulders', 'back'],
    measurementType: 'distance',
    defaultRestSeconds: 0,
    equipment: ['machine'],
    instructions: [
      'Smooth stride, push and pull through the handles for a full-body effort.',
      'The machine will give you distance + duration to log.',
    ],
  }),
  compound({
    id: 'plank',
    name: 'Plank',
    category: 'core',
    primary: ['core'],
    secondary: ['shoulders'],
    measurementType: 'time_seconds',
    defaultRestSeconds: 60,
    equipment: ['bodyweight', 'yoga-mat'],
    diagram: 'plank',
    instructions: [
      'Forearms on the floor, elbows under shoulders.',
      'Body straight head-to-heels — squeeze glutes and abs.',
      'Breathe steadily; hold for the prescribed time.',
    ],
  }),
];
