// AUTOGENERATED by scripts/build-seed.py — do not edit by hand.
// Source: workout-tracker/strong-curves.xlsx
// Run `pnpm seed:build` after the source spreadsheet changes.

import type { Exercise, RoutineTemplate } from '../types';

// Note: `requiredEquipment` / `instructions` / `diagram` are layered
// on at seed-load time by `src/db/seed-loader.ts` from the enrichment
// map. The generator omits them so it doesn't need to know about
// equipment tagging.
export const STRONG_CURVES_EXERCISES: ReadonlyArray<
  Omit<Exercise, 'isCustom' | 'profileId' | 'requiredEquipment' | 'instructions' | 'diagram'>
> = [
  {
    id: "25-lb-back-extension-reverse-hype",
    name: "25 lb Back Extension /Reverse Hype",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "25-lb-back-extension-reverse-hyper",
    name: "25 lb Back Extension /Reverse Hyper",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "band-anti-rotation-hold",
    name: "Band Anti Rotation Hold",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    category: "push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    measurementType: "weight_reps",
    defaultRestSeconds: 120,
    perSide: false,
    usesBarbell: true,
  },
  {
    id: "barbell-close-grip-bench-press",
    name: "Barbell Close Grip Bench Press",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "barbell-dumbbell-bench-press",
    name: "Barbell/Dumbbell Bench Press",
    category: "push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    measurementType: "weight_reps",
    defaultRestSeconds: 90,
    perSide: false,
    usesBarbell: true,
  },
  {
    id: "barbell-romanian-deadlift",
    name: "Barbell Romanian Deadlift",
    category: "hip-hinge",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["back"],
    measurementType: "weight_reps",
    defaultRestSeconds: 120,
    perSide: false,
    usesBarbell: true,
  },
  {
    id: "body-weight-negative-pushup",
    name: "Body Weight Negative Pushup",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "bodyweight-barbell-box-squat",
    name: "Bodyweight/Barbell Box Squat",
    category: "quad",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    measurementType: "weight_reps",
    defaultRestSeconds: 120,
    perSide: false,
    usesBarbell: true,
  },
  {
    id: "bodyweight-barbell-glute-bridge",
    name: "Bodyweight/Barbell Glute Bridge",
    category: "glute",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    measurementType: "weight_reps",
    defaultRestSeconds: 90,
    perSide: false,
    usesBarbell: true,
  },
  {
    id: "bodyweight-dumbbell-single-leg-rdl",
    name: "Bodyweight/Dumbbell Single Leg RDL",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "bodyweight-dumbbell-squat",
    name: "Bodyweight/Dumbbell Squat",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "bodyweight-dumbbell-step-up",
    name: "Bodyweight/Dumbbell Step Up",
    category: "quad",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    measurementType: "reps_each_side",
    defaultRestSeconds: 60,
    perSide: true,
    usesBarbell: false,
  },
  {
    id: "bodyweight-hip-hinge-with-dowel",
    name: "Bodyweight Hip Hinge with Dowel",
    category: "hip-hinge",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["back"],
    measurementType: "bodyweight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "bodyweight-hip-thrust",
    name: "Bodyweight Hip Thrust",
    category: "glute",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    measurementType: "bodyweight_reps",
    defaultRestSeconds: 90,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "bodyweight-or-45-lb-back-extension",
    name: "Bodyweight or 45 lb Back Extension",
    category: "hip-hinge",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["back"],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "bodyweight-step-up-reverse-lunge-combo",
    name: "Bodyweight Step Up/Reverse Lunge Combo",
    category: "quad",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    measurementType: "bodyweight_reps",
    defaultRestSeconds: 60,
    perSide: true,
    usesBarbell: false,
  },
  {
    id: "bodyweight-swiss-ball-45-degree-back-extension",
    name: "Bodyweight Swiss Ball 45 Degree Back Extension",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "bodyweight-walking-lunge",
    name: "Bodyweight Walking Lunge",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "crunch",
    name: "Crunch",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "dumbbell-incline-press",
    name: "Dumbbell Incline Press",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "dumbbell-military-press-standing",
    name: "Dumbbell Military Press, Standing",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "dumbbell-romanian-deadlift",
    name: "Dumbbell Romanian Deadlift",
    category: "hip-hinge",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["back"],
    measurementType: "weight_reps",
    defaultRestSeconds: 90,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "elevated-foot-rkc-plank",
    name: "Elevated Foot RKC Plank",
    category: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: ["glutes"],
    measurementType: "time_seconds",
    defaultRestSeconds: 45,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "front-lat-pulldowns",
    name: "Front Lat Pulldowns",
    category: "pull",
    primaryMuscles: ["lats", "back"],
    secondaryMuscles: ["biceps"],
    measurementType: "weight_reps",
    defaultRestSeconds: 90,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "glute-march",
    name: "Glute March",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "knee-pushups",
    name: "Knee Pushups",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "modified-inverted-row-bar-t-bar-row",
    name: "Modified Inverted Row (bar)/ T Bar Row",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "negative-chin-up-underhand-grip-pull-down",
    name: "Negative Chin Up/Underhand Grip Pull Down",
    category: "pull",
    primaryMuscles: ["lats", "back"],
    secondaryMuscles: ["biceps"],
    measurementType: "bodyweight_reps",
    defaultRestSeconds: 90,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "one-arm-dumbbell-row",
    name: "One Arm Dumbbell Row",
    category: "pull",
    primaryMuscles: ["back", "lats"],
    secondaryMuscles: ["biceps"],
    measurementType: "reps_each_side",
    defaultRestSeconds: 60,
    perSide: true,
    usesBarbell: false,
  },
  {
    id: "one-arm-dumbbell-row-or-band-pull-or-row-with-bar",
    name: "One Arm Dumbbell Row or band pull or row with bar",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "rkc-plank",
    name: "RKC Plank",
    category: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    measurementType: "time_seconds",
    defaultRestSeconds: 45,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "rope-horizontal-chop",
    name: "Rope Horizontal Chop",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "russian-kettlebell-swing",
    name: "Russian Kettlebell Swing",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "seated-row",
    name: "Seated Row",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "side-crunch",
    name: "Side Crunch",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "side-lying-abduction",
    name: "Side Lying Abduction",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "side-lying-abductions",
    name: "Side Lying Abductions",
    category: "accessory",
    primaryMuscles: ["abductors", "glutes"],
    secondaryMuscles: [],
    measurementType: "reps_each_side",
    defaultRestSeconds: 45,
    perSide: true,
    usesBarbell: false,
  },
  {
    id: "side-lying-clam",
    name: "Side Lying Clam",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "side-plank",
    name: "Side plank",
    category: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: ["abductors"],
    measurementType: "time_seconds",
    defaultRestSeconds: 30,
    perSide: true,
    usesBarbell: false,
  },
  {
    id: "side-plank-on-feet",
    name: "Side plank on feet",
    category: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: ["abductors"],
    measurementType: "time_seconds",
    defaultRestSeconds: 30,
    perSide: true,
    usesBarbell: false,
  },
  {
    id: "single-leg-glute-bridge",
    name: "Single-Leg Glute Bridge",
    category: "glute",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    measurementType: "reps_each_side",
    defaultRestSeconds: 60,
    perSide: true,
    usesBarbell: false,
  },
  {
    id: "standing-single-arm-cable-row",
    name: "Standing Single Arm Cable Row",
    category: "pull",
    primaryMuscles: ["back", "lats"],
    secondaryMuscles: ["biceps"],
    measurementType: "reps_each_side",
    defaultRestSeconds: 60,
    perSide: true,
    usesBarbell: false,
  },
  {
    id: "straight-leg-sit-up",
    name: "Straight Leg Sit Up",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "swiss-ball-crunch",
    name: "Swiss Ball Crunch",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "swiss-ball-side-crunch",
    name: "Swiss Ball Side Crunch",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "torso-elevated-push-up",
    name: "Torso Elevated Push Up",
    category: "push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders", "core"],
    measurementType: "bodyweight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "towel-row",
    name: "Towel Row",
    category: "pull",
    primaryMuscles: ["back", "lats"],
    secondaryMuscles: ["biceps"],
    measurementType: "bodyweight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
  {
    id: "x-band-walk-or-cable-hip-abductions",
    name: "X-Band Walk (or, Cable Hip Abductions)",
    category: "other",
    primaryMuscles: [],
    secondaryMuscles: [],
    measurementType: "weight_reps",
    defaultRestSeconds: 60,
    perSide: false,
    usesBarbell: false,
  },
] as const;

type SeedRoutine = Omit<RoutineTemplate, 'profileId' | 'createdAt' | 'updatedAt'>;

export const STRONG_CURVES_ROUTINES: ReadonlyArray<SeedRoutine> = [
  {
    id: "strong-curves-bootyful-beginnings",
    name: "Strong Curves — Bootyful Beginnings",
    description: "Bret Contreras' beginner glute-focused programme. Four workouts a week (A/B/A/C) over 8 weeks. Mixes barbell, dumbbell, and bodyweight work.",
    isSeed: true,
    weeks: [
      { weekNumber: 1, days: [
        { dayNumber: 1, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-glute-bridge", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "one-arm-dumbbell-row", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-box-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-dumbbell-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "dumbbell-romanian-deadlift", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 2, kind: 'workout', workoutLabel: "B", blocks: [
          { type: "single", exercises: [
            { exerciseId: "single-leg-glute-bridge", setCount: 3, reps: { min: 10, max: 20 }, perSide: true, notes: "can elevate foot on bench" },
          ] },
          { type: "single", exercises: [
            { exerciseId: "front-lat-pulldowns", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-dumbbell-step-up", setCount: 3, reps: { min: 10, max: 20 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "dumbbell-military-press-standing", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-or-45-lb-back-extension", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-clam", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "crunch", setCount: 1, reps: { min: 15, max: 30 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-crunch", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
        ] },
        { dayNumber: 3, kind: 'rest', blocks: [] },
        { dayNumber: 4, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-glute-bridge", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "one-arm-dumbbell-row", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-box-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-dumbbell-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "dumbbell-romanian-deadlift", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 5, kind: 'workout', workoutLabel: "C", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "glute-march", setCount: 3, notes: "Can do with back on bench" },
            { exerciseId: "seated-row", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-dumbbell-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "dumbbell-incline-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-dumbbell-single-leg-rdl", setCount: 2, reps: { min: 10, max: 20 }, perSide: true, notes: "(Romanian Deadlift)" },
          ] },
          { type: "single", exercises: [
            { exerciseId: "x-band-walk-or-cable-hip-abductions", setCount: 1 },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rope-horizontal-chop", setCount: 1, perSide: true },
          ] },
        ] },
        { dayNumber: 6, kind: 'rest', blocks: [] },
        { dayNumber: 7, kind: 'rest', blocks: [] },
      ] },
      { weekNumber: 2, days: [
        { dayNumber: 1, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-glute-bridge", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "one-arm-dumbbell-row", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-box-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-dumbbell-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "dumbbell-romanian-deadlift", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 2, kind: 'workout', workoutLabel: "B", blocks: [
          { type: "single", exercises: [
            { exerciseId: "single-leg-glute-bridge", setCount: 3, reps: { min: 10, max: 20 }, perSide: true, notes: "can elevate foot on bench" },
          ] },
          { type: "single", exercises: [
            { exerciseId: "front-lat-pulldowns", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-dumbbell-step-up", setCount: 3, reps: { min: 10, max: 20 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "dumbbell-military-press-standing", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-or-45-lb-back-extension", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-clam", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "crunch", setCount: 1, reps: { min: 15, max: 30 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-crunch", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
        ] },
        { dayNumber: 3, kind: 'rest', blocks: [] },
        { dayNumber: 4, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-glute-bridge", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "one-arm-dumbbell-row", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-box-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-dumbbell-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "dumbbell-romanian-deadlift", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 5, kind: 'workout', workoutLabel: "C", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "glute-march", setCount: 3, notes: "Can do with back on bench" },
            { exerciseId: "seated-row", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-dumbbell-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "dumbbell-incline-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-dumbbell-single-leg-rdl", setCount: 2, reps: { min: 10, max: 20 }, perSide: true, notes: "(Romanian Deadlift)" },
          ] },
          { type: "single", exercises: [
            { exerciseId: "x-band-walk-or-cable-hip-abductions", setCount: 1 },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rope-horizontal-chop", setCount: 1, perSide: true },
          ] },
        ] },
        { dayNumber: 6, kind: 'rest', blocks: [] },
        { dayNumber: 7, kind: 'rest', blocks: [] },
      ] },
      { weekNumber: 3, days: [
        { dayNumber: 1, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-glute-bridge", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "one-arm-dumbbell-row", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-box-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-dumbbell-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "dumbbell-romanian-deadlift", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 2, kind: 'workout', workoutLabel: "B", blocks: [
          { type: "single", exercises: [
            { exerciseId: "single-leg-glute-bridge", setCount: 3, reps: { min: 10, max: 20 }, perSide: true, notes: "can elevate foot on bench" },
          ] },
          { type: "single", exercises: [
            { exerciseId: "front-lat-pulldowns", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-dumbbell-step-up", setCount: 3, reps: { min: 10, max: 20 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "dumbbell-military-press-standing", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-or-45-lb-back-extension", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-clam", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "crunch", setCount: 1, reps: { min: 15, max: 30 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-crunch", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
        ] },
        { dayNumber: 3, kind: 'rest', blocks: [] },
        { dayNumber: 4, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-glute-bridge", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "one-arm-dumbbell-row", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-box-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-dumbbell-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "dumbbell-romanian-deadlift", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 5, kind: 'workout', workoutLabel: "C", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "glute-march", setCount: 3, notes: "Can do with back on bench" },
            { exerciseId: "seated-row", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-dumbbell-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "dumbbell-incline-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-dumbbell-single-leg-rdl", setCount: 2, reps: { min: 10, max: 20 }, perSide: true, notes: "(Romanian Deadlift)" },
          ] },
          { type: "single", exercises: [
            { exerciseId: "x-band-walk-or-cable-hip-abductions", setCount: 1 },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rope-horizontal-chop", setCount: 1, perSide: true },
          ] },
        ] },
        { dayNumber: 6, kind: 'rest', blocks: [] },
        { dayNumber: 7, kind: 'rest', blocks: [] },
      ] },
      { weekNumber: 4, days: [
        { dayNumber: 1, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-glute-bridge", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "one-arm-dumbbell-row", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-box-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-dumbbell-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "dumbbell-romanian-deadlift", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 2, kind: 'workout', workoutLabel: "B", blocks: [
          { type: "single", exercises: [
            { exerciseId: "single-leg-glute-bridge", setCount: 3, reps: { min: 10, max: 20 }, perSide: true, notes: "can elevate foot on bench" },
          ] },
          { type: "single", exercises: [
            { exerciseId: "front-lat-pulldowns", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-dumbbell-step-up", setCount: 3, reps: { min: 10, max: 20 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "dumbbell-military-press-standing", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-or-45-lb-back-extension", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-clam", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "crunch", setCount: 1, reps: { min: 15, max: 30 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-crunch", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
        ] },
        { dayNumber: 3, kind: 'rest', blocks: [] },
        { dayNumber: 4, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-glute-bridge", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "one-arm-dumbbell-row", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-box-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-dumbbell-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "dumbbell-romanian-deadlift", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 5, kind: 'workout', workoutLabel: "C", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "glute-march", setCount: 3, notes: "Can do with back on bench" },
            { exerciseId: "seated-row", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-dumbbell-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "dumbbell-incline-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-dumbbell-single-leg-rdl", setCount: 2, reps: { min: 10, max: 20 }, perSide: true, notes: "(Romanian Deadlift)" },
          ] },
          { type: "single", exercises: [
            { exerciseId: "x-band-walk-or-cable-hip-abductions", setCount: 1 },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rope-horizontal-chop", setCount: 1, perSide: true },
          ] },
        ] },
        { dayNumber: 6, kind: 'rest', blocks: [] },
        { dayNumber: 7, kind: 'rest', blocks: [] },
      ] },
      { weekNumber: 5, days: [
        { dayNumber: 1, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-hip-thrust", setCount: 3, reps: { min: 10, max: 20 }, notes: "Back on bench" },
            { exerciseId: "standing-single-arm-cable-row", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-step-up-reverse-lunge-combo", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "barbell-romanian-deadlift", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "elevated-foot-rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 60 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank-on-feet", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 2, kind: 'workout', workoutLabel: "B", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "single-leg-glute-bridge", setCount: 3, reps: { min: 10, max: 20 }, perSide: true, notes: "can elevate foot on bench" },
            { exerciseId: "negative-chin-up-underhand-grip-pull-down", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-walking-lunge", setCount: 3, reps: { min: 10, max: 20 }, perSide: true },
            { exerciseId: "dumbbell-military-press-standing", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "25-lb-back-extension-reverse-hype", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-clam", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "swiss-ball-crunch", setCount: 1, reps: { min: 15, max: 30 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "swiss-ball-side-crunch", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
        ] },
        { dayNumber: 3, kind: 'rest', blocks: [] },
        { dayNumber: 4, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-hip-thrust", setCount: 3, reps: { min: 10, max: 20 }, notes: "Back on bench" },
            { exerciseId: "standing-single-arm-cable-row", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-step-up-reverse-lunge-combo", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "barbell-romanian-deadlift", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "elevated-foot-rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 60 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank-on-feet", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 5, kind: 'workout', workoutLabel: "C", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-hip-thrust", setCount: 3, reps: { min: 10, max: 20 }, notes: "Can do with back on bench" },
            { exerciseId: "modified-inverted-row-bar-t-bar-row", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "goblet-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-close-grip-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "russian-kettlebell-swing", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "x-band-walk-or-cable-hip-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "straight-leg-sit-up", setCount: 1, reps: { min: 15, max: 30 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "band-anti-rotation-hold", setCount: 1, durationSeconds: { min: 10, max: 20 }, perSide: true },
          ] },
        ] },
        { dayNumber: 6, kind: 'rest', blocks: [] },
        { dayNumber: 7, kind: 'rest', blocks: [] },
      ] },
      { weekNumber: 6, days: [
        { dayNumber: 1, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-hip-thrust", setCount: 3, reps: { min: 10, max: 20 }, notes: "Back on bench" },
            { exerciseId: "standing-single-arm-cable-row", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-step-up-reverse-lunge-combo", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "barbell-romanian-deadlift", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "elevated-foot-rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 60 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank-on-feet", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 2, kind: 'workout', workoutLabel: "B", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "single-leg-glute-bridge", setCount: 3, reps: { min: 10, max: 20 }, perSide: true, notes: "can elevate foot on bench" },
            { exerciseId: "negative-chin-up-underhand-grip-pull-down", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-walking-lunge", setCount: 3, reps: { min: 10, max: 20 }, perSide: true },
            { exerciseId: "dumbbell-military-press-standing", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "25-lb-back-extension-reverse-hype", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-clam", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "swiss-ball-crunch", setCount: 1, reps: { min: 15, max: 30 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "swiss-ball-side-crunch", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
        ] },
        { dayNumber: 3, kind: 'rest', blocks: [] },
        { dayNumber: 4, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-hip-thrust", setCount: 3, reps: { min: 10, max: 20 }, notes: "Back on bench" },
            { exerciseId: "standing-single-arm-cable-row", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-step-up-reverse-lunge-combo", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "barbell-romanian-deadlift", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "elevated-foot-rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 60 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank-on-feet", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 5, kind: 'workout', workoutLabel: "C", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-hip-thrust", setCount: 3, reps: { min: 10, max: 20 }, notes: "Can do with back on bench" },
            { exerciseId: "modified-inverted-row-bar-t-bar-row", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "goblet-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-close-grip-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "russian-kettlebell-swing", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "x-band-walk-or-cable-hip-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "straight-leg-sit-up", setCount: 1, reps: { min: 15, max: 30 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "band-anti-rotation-hold", setCount: 1, durationSeconds: { min: 10, max: 20 }, perSide: true },
          ] },
        ] },
        { dayNumber: 6, kind: 'rest', blocks: [] },
        { dayNumber: 7, kind: 'rest', blocks: [] },
      ] },
      { weekNumber: 7, days: [
        { dayNumber: 1, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-hip-thrust", setCount: 3, reps: { min: 10, max: 20 }, notes: "Back on bench" },
            { exerciseId: "standing-single-arm-cable-row", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-step-up-reverse-lunge-combo", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "barbell-romanian-deadlift", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "elevated-foot-rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 60 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank-on-feet", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 2, kind: 'workout', workoutLabel: "B", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "single-leg-glute-bridge", setCount: 3, reps: { min: 10, max: 20 }, perSide: true, notes: "can elevate foot on bench" },
            { exerciseId: "negative-chin-up-underhand-grip-pull-down", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-walking-lunge", setCount: 3, reps: { min: 10, max: 20 }, perSide: true },
            { exerciseId: "dumbbell-military-press-standing", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "25-lb-back-extension-reverse-hype", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-clam", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "swiss-ball-crunch", setCount: 1, reps: { min: 15, max: 30 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "swiss-ball-side-crunch", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
        ] },
        { dayNumber: 3, kind: 'rest', blocks: [] },
        { dayNumber: 4, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-hip-thrust", setCount: 3, reps: { min: 10, max: 20 }, notes: "Back on bench" },
            { exerciseId: "standing-single-arm-cable-row", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-step-up-reverse-lunge-combo", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "barbell-romanian-deadlift", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "elevated-foot-rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 60 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank-on-feet", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 5, kind: 'workout', workoutLabel: "C", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-hip-thrust", setCount: 3, reps: { min: 10, max: 20 }, notes: "Can do with back on bench" },
            { exerciseId: "modified-inverted-row-bar-t-bar-row", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "goblet-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-close-grip-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "russian-kettlebell-swing", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "x-band-walk-or-cable-hip-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "straight-leg-sit-up", setCount: 1, reps: { min: 15, max: 30 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "band-anti-rotation-hold", setCount: 1, durationSeconds: { min: 10, max: 20 }, perSide: true },
          ] },
        ] },
        { dayNumber: 6, kind: 'rest', blocks: [] },
        { dayNumber: 7, kind: 'rest', blocks: [] },
      ] },
      { weekNumber: 8, days: [
        { dayNumber: 1, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-hip-thrust", setCount: 3, reps: { min: 10, max: 20 }, notes: "Back on bench" },
            { exerciseId: "standing-single-arm-cable-row", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-step-up-reverse-lunge-combo", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "barbell-romanian-deadlift", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "elevated-foot-rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 60 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank-on-feet", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 2, kind: 'workout', workoutLabel: "B", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "single-leg-glute-bridge", setCount: 3, reps: { min: 10, max: 20 }, perSide: true, notes: "can elevate foot on bench" },
            { exerciseId: "negative-chin-up-underhand-grip-pull-down", setCount: 3, reps: { min: 8, max: 12 }, notes: "Chin Up machine" },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-walking-lunge", setCount: 3, reps: { min: 10, max: 20 }, perSide: true },
            { exerciseId: "dumbbell-military-press-standing", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "25-lb-back-extension-reverse-hyper", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-clam", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "swiss-ball-crunch", setCount: 1, reps: { min: 15, max: 30 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "swiss-ball-side-crunch", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
        ] },
        { dayNumber: 3, kind: 'rest', blocks: [] },
        { dayNumber: 4, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-hip-thrust", setCount: 3, reps: { min: 10, max: 20 }, notes: "Back on bench" },
            { exerciseId: "standing-single-arm-cable-row", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-step-up-reverse-lunge-combo", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "barbell-romanian-deadlift", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "elevated-foot-rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 60 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank-on-feet", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 5, kind: 'workout', workoutLabel: "C", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-hip-thrust", setCount: 3, reps: { min: 10, max: 20 }, notes: "Can do with back on bench" },
            { exerciseId: "modified-inverted-row-bar-t-bar-row", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "goblet-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "barbell-close-grip-bench-press", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "russian-kettlebell-swing", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "x-band-walk-or-cable-hip-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "straight-leg-sit-up", setCount: 1, reps: { min: 15, max: 30 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "band-anti-rotation-hold", setCount: 1, durationSeconds: { min: 10, max: 20 }, perSide: true },
          ] },
        ] },
        { dayNumber: 6, kind: 'rest', blocks: [] },
        { dayNumber: 7, kind: 'rest', blocks: [] },
      ] },
    ],
  },
  {
    id: "strong-curves-bodyweight",
    name: "Strong Curves — Bodyweight",
    description: "Equipment-free variant of Bootyful Beginnings. Four workouts a week (A/B/A/C) over 4 weeks.",
    isSeed: true,
    weeks: [
      { weekNumber: 1, days: [
        { dayNumber: 1, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-glute-bridge", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "one-arm-dumbbell-row-or-band-pull-or-row-with-bar", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-box-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "torso-elevated-push-up", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-hip-hinge-with-dowel", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 2, kind: 'workout', workoutLabel: "B", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "single-leg-glute-bridge", setCount: 3, reps: { min: 10, max: 20 }, perSide: true, notes: "can elevate foot on bench" },
            { exerciseId: "towel-row", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-dumbbell-step-up", setCount: 3, reps: { min: 10, max: 20 }, perSide: true },
            { exerciseId: "knee-pushups", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-swiss-ball-45-degree-back-extension", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-clam", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "crunch", setCount: 1, reps: { min: 15, max: 30 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-crunch", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
        ] },
        { dayNumber: 3, kind: 'rest', blocks: [] },
        { dayNumber: 4, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-glute-bridge", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "one-arm-dumbbell-row-or-band-pull-or-row-with-bar", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-box-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "torso-elevated-push-up", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-hip-hinge-with-dowel", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 5, kind: 'workout', workoutLabel: "C", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "glute-march", setCount: 3, notes: "Can do with back on bench" },
            { exerciseId: "towel-row", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-dumbbell-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "body-weight-negative-pushup", setCount: 3, reps: { min: 3, max: 5 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-dumbbell-single-leg-rdl", setCount: 2, reps: { min: 10, max: 20 }, perSide: true, notes: "(Romanian Deadlift)" },
          ] },
          { type: "single", exercises: [
            { exerciseId: "straight-leg-sit-up", setCount: 1, reps: { min: 15, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abduction", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "swiss-ball-side-crunch", setCount: 1, perSide: true },
          ] },
        ] },
        { dayNumber: 6, kind: 'rest', blocks: [] },
        { dayNumber: 7, kind: 'rest', blocks: [] },
      ] },
      { weekNumber: 2, days: [
        { dayNumber: 1, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-glute-bridge", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "one-arm-dumbbell-row-or-band-pull-or-row-with-bar", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-box-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "torso-elevated-push-up", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-hip-hinge-with-dowel", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 2, kind: 'workout', workoutLabel: "B", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "single-leg-glute-bridge", setCount: 3, reps: { min: 10, max: 20 }, perSide: true, notes: "can elevate foot on bench" },
            { exerciseId: "towel-row", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-dumbbell-step-up", setCount: 3, reps: { min: 10, max: 20 }, perSide: true },
            { exerciseId: "knee-pushups", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-swiss-ball-45-degree-back-extension", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-clam", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "crunch", setCount: 1, reps: { min: 15, max: 30 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-crunch", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
        ] },
        { dayNumber: 3, kind: 'rest', blocks: [] },
        { dayNumber: 4, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-glute-bridge", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "one-arm-dumbbell-row-or-band-pull-or-row-with-bar", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-box-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "torso-elevated-push-up", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-hip-hinge-with-dowel", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 5, kind: 'workout', workoutLabel: "C", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "glute-march", setCount: 3, notes: "Can do with back on bench" },
            { exerciseId: "towel-row", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-dumbbell-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "body-weight-negative-pushup", setCount: 3, reps: { min: 3, max: 5 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-dumbbell-single-leg-rdl", setCount: 2, reps: { min: 10, max: 20 }, perSide: true, notes: "(Romanian Deadlift)" },
          ] },
          { type: "single", exercises: [
            { exerciseId: "straight-leg-sit-up", setCount: 1, reps: { min: 15, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abduction", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "swiss-ball-side-crunch", setCount: 1, perSide: true },
          ] },
        ] },
        { dayNumber: 6, kind: 'rest', blocks: [] },
        { dayNumber: 7, kind: 'rest', blocks: [] },
      ] },
      { weekNumber: 3, days: [
        { dayNumber: 1, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-glute-bridge", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "one-arm-dumbbell-row-or-band-pull-or-row-with-bar", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-box-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "torso-elevated-push-up", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-hip-hinge-with-dowel", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 2, kind: 'workout', workoutLabel: "B", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "single-leg-glute-bridge", setCount: 3, reps: { min: 10, max: 20 }, perSide: true, notes: "can elevate foot on bench" },
            { exerciseId: "towel-row", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-dumbbell-step-up", setCount: 3, reps: { min: 10, max: 20 }, perSide: true },
            { exerciseId: "knee-pushups", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-swiss-ball-45-degree-back-extension", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-clam", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "crunch", setCount: 1, reps: { min: 15, max: 30 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-crunch", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
        ] },
        { dayNumber: 3, kind: 'rest', blocks: [] },
        { dayNumber: 4, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-glute-bridge", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "one-arm-dumbbell-row-or-band-pull-or-row-with-bar", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-box-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "torso-elevated-push-up", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-hip-hinge-with-dowel", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 5, kind: 'workout', workoutLabel: "C", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "glute-march", setCount: 3, notes: "Can do with back on bench" },
            { exerciseId: "towel-row", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-dumbbell-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "body-weight-negative-pushup", setCount: 3, reps: { min: 3, max: 5 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-dumbbell-single-leg-rdl", setCount: 2, reps: { min: 10, max: 20 }, perSide: true, notes: "(Romanian Deadlift)" },
          ] },
          { type: "single", exercises: [
            { exerciseId: "straight-leg-sit-up", setCount: 1, reps: { min: 15, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abduction", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "swiss-ball-side-crunch", setCount: 1, perSide: true },
          ] },
        ] },
        { dayNumber: 6, kind: 'rest', blocks: [] },
        { dayNumber: 7, kind: 'rest', blocks: [] },
      ] },
      { weekNumber: 4, days: [
        { dayNumber: 1, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-glute-bridge", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "one-arm-dumbbell-row-or-band-pull-or-row-with-bar", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-box-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "torso-elevated-push-up", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-hip-hinge-with-dowel", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 2, kind: 'workout', workoutLabel: "B", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "single-leg-glute-bridge", setCount: 3, reps: { min: 10, max: 20 }, perSide: true, notes: "can elevate foot on bench" },
            { exerciseId: "towel-row", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-dumbbell-step-up", setCount: 3, reps: { min: 10, max: 20 }, perSide: true },
            { exerciseId: "knee-pushups", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-swiss-ball-45-degree-back-extension", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-clam", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "crunch", setCount: 1, reps: { min: 15, max: 30 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-crunch", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
        ] },
        { dayNumber: 3, kind: 'rest', blocks: [] },
        { dayNumber: 4, kind: 'workout', workoutLabel: "A", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-glute-bridge", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "one-arm-dumbbell-row-or-band-pull-or-row-with-bar", setCount: 3, reps: { min: 8, max: 12 }, perSide: true },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-barbell-box-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "torso-elevated-push-up", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-hip-hinge-with-dowel", setCount: 3, reps: { min: 10, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abductions", setCount: 1, reps: { min: 15, max: 30 }, perSide: true },
          ] },
          { type: "single", exercises: [
            { exerciseId: "rkc-plank", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-plank", setCount: 1, durationSeconds: { min: 20, max: 60 }, perSide: true },
          ] },
        ] },
        { dayNumber: 5, kind: 'workout', workoutLabel: "C", blocks: [
          { type: "superset", exercises: [
            { exerciseId: "glute-march", setCount: 3, notes: "Can do with back on bench" },
            { exerciseId: "towel-row", setCount: 3, reps: { min: 8, max: 12 } },
          ] },
          { type: "superset", exercises: [
            { exerciseId: "bodyweight-dumbbell-squat", setCount: 3, reps: { min: 10, max: 20 } },
            { exerciseId: "body-weight-negative-pushup", setCount: 3, reps: { min: 3, max: 5 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "bodyweight-dumbbell-single-leg-rdl", setCount: 2, reps: { min: 10, max: 20 }, perSide: true, notes: "(Romanian Deadlift)" },
          ] },
          { type: "single", exercises: [
            { exerciseId: "straight-leg-sit-up", setCount: 1, reps: { min: 15, max: 20 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "side-lying-abduction", setCount: 1, durationSeconds: { min: 20, max: 120 } },
          ] },
          { type: "single", exercises: [
            { exerciseId: "swiss-ball-side-crunch", setCount: 1, perSide: true },
          ] },
        ] },
        { dayNumber: 6, kind: 'rest', blocks: [] },
        { dayNumber: 7, kind: 'rest', blocks: [] },
      ] },
    ],
  },
] as const;
